# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatexample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chatexample
 # ios 自动控制输入框位置
	pod 'IQKeyboardManager'

  # 拍照组件
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
#  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  # 图片流形式上传插件
	pod 'react-native-fetch-blob',
    :path => '../node_modules/react-native-fetch-blob'

  target 'chatexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chatexample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chatexample-tvOS

  target 'chatexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
